# -*- coding: utf-8 -*-
"""CNN_Pollos_Completo .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19pdpDA0zk610jrwChgDDzIQMk3SK66zr

# UNIVERSIDAD DE CUNDINAMARCA

---

## CLASIFICACIÓN DE ENFERMEDADES EN POLLOS MEDIANTE REDES NEURONALES CONVOLUCIONALES (CNN)

---

### Introducción

El avance de la inteligencia artificial y el aprendizaje profundo ha abierto nuevas posibilidades para resolver problemas del sector agropecuario. Las Redes Neuronales Convolucionales (CNN) representan una de las herramientas más poderosas dentro del campo de la visión artificial, siendo capaces de analizar y clasificar imágenes con una precisión comparable a la del ojo humano.

El presente proyecto aplica esta tecnología al diagnóstico automático de enfermedades en pollos, un problema de alto impacto económico en la industria avícola. A través del entrenamiento de una CNN con un dataset de 8.067 imágenes, el modelo aprende a identificar cuatro condiciones: pollos sanos, Coccidiosis, Salmonella y New Castle Disease, sin intervención humana en el proceso de análisis.

---

| | |
|---|---|
| **Materia** | Deep Learning (Fundamentos) |
| **Profesor** | Ing. Jorge Mican |
| **Integrante** | Andrés Felipe Díaz Campos |
| **Programa** | Ingeniería de Sistemas |
| **Universidad** | Universidad de Cundinamarca |
| **Año** | 2026 |

---

# CNN — Clasificacion de Enfermedades en Pollos

**Objetivo:** Clasificar imagenes de pollos en 4 categorias usando una CNN.

| Clase | Descripcion |
|-------|-------------|
| Healthy | Pollo sano |
| Coccidiosis | Infeccion parasitaria intestinal |
| Salmonella | Infeccion bacteriana |
| New Castle Disease | Enfermedad viral respiratoria |

**Dataset:** https://www.kaggle.com/datasets/allandclive/chicken-disease-1  
**Framework:** TensorFlow / Keras  
**Entorno:** Google Colab con GPU T4

---
## PASO 1 — Instalacion de dependencias
"""

!pip install kaggle --quiet

import tensorflow as tf
print('TensorFlow version:', tf.__version__)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print('GPU disponible:', gpus[0].name)
else:
    print('ADVERTENCIA: No hay GPU. Ve a Entorno de ejecucion > Cambiar tipo de entorno > GPU T4')

"""---
## PASO 2 — Credenciales de Kaggle

Reemplaza TU_USUARIO y TU_KEY con tus datos de kaggle.com > Settings > API > Create New Token

"""

import os

os.environ['KAGGLE_USERNAME'] = 'andres1003'
os.environ['KAGGLE_KEY']      = 'KGAT_c7af204ce0f1a56827240aa8f4476ece'

usuario = os.environ.get('KAGGLE_USERNAME', 'NO CONFIGURADO')
clave   = os.environ.get('KAGGLE_KEY', 'NO CONFIGURADO')
print('Usuario:', usuario)
print('Key:', clave[:8] + '...' if clave != 'NO CONFIGURADO' else 'NO CONFIGURADA')

"""---
## PASO 3 — Descarga del dataset

"""

import zipfile

print('Descargando dataset...')
!kaggle datasets download -d allandclive/chicken-disease-1

zip_file = 'chicken-disease-1.zip'
if os.path.exists(zip_file):
    size_mb = os.path.getsize(zip_file) / (1024*1024)
    print(f'Descargado: {size_mb:.1f} MB')
    with zipfile.ZipFile(zip_file, 'r') as z:
        z.extractall('.')
    print('Dataset descomprimido correctamente')
else:
    print('ERROR: No se pudo descargar. Verifica tus credenciales.')

!ls -la

"""---
## PASO 4 — Importacion de librerias

"""

import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D, MaxPooling2D, BatchNormalization,
    Flatten, Dense, Dropout
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

from google.colab import files

sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 100

SEMILLA = 42
np.random.seed(SEMILLA)
tf.random.set_seed(SEMILLA)

print('Librerias importadas correctamente')

"""---
## PASO 5 — Exploracion del dataset

El dataset viene con un CSV que mapea cada imagen a su etiqueta.
Analizamos la distribucion de clases antes de entrenar.

"""

df = pd.read_csv('train_data.csv')

print('Primeras filas:')
print(df.head(10))
print()
print('Total de imagenes:', len(df))
print('Columnas:', list(df.columns))
print()
print('Distribucion de clases:')
print(df['label'].value_counts())

conteo = df['label'].value_counts()
colores = ['#2ecc71', '#e74c3c', '#3498db', '#f39c12']

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Distribucion de Clases en el Dataset', fontsize=14, fontweight='bold')

axes[0].bar(conteo.index, conteo.values, color=colores, edgecolor='black', linewidth=0.7)
axes[0].set_title('Cantidad por clase')
axes[0].set_xlabel('Clase')
axes[0].set_ylabel('Imagenes')
axes[0].tick_params(axis='x', rotation=15)
for i, v in enumerate(conteo.values):
    axes[0].text(i, v + 30, str(v), ha='center', fontweight='bold')

axes[1].pie(conteo.values, labels=conteo.index, autopct='%1.1f%%',
            colors=colores, startangle=140,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[1].set_title('Porcentaje por clase')

plt.tight_layout()
plt.savefig('distribucion_clases.png', bbox_inches='tight')
plt.show()

ratio = conteo.max() / conteo.min()
print(f'Ratio de desbalance: {ratio:.2f}x')
if ratio > 3:
    print('ADVERTENCIA: Dataset desbalanceado.')
else:
    print('Dataset relativamente balanceado.')

"""---
## PASO 6 — Preparacion del dataset

- Construimos la ruta completa de cada imagen
- Dividimos en 80% entrenamiento y 20% validacion
- `stratify` mantiene la proporcion de clases en ambos conjuntos

"""

IMG_DIR = 'Train'

df['ruta'] = df['images'].apply(lambda nombre: os.path.join(IMG_DIR, nombre))
df['existe'] = df['ruta'].apply(os.path.exists)

print(f'Imagenes encontradas: {df["existe"].sum()} / {len(df)}')
print(f'Imagenes faltantes:   {(~df["existe"]).sum()}')

df = df[df['existe']].reset_index(drop=True)

df_train, df_val = train_test_split(
    df, test_size=0.2, random_state=SEMILLA, stratify=df['label']
)

print(f'Entrenamiento: {len(df_train)} imagenes')
print(f'Validacion:    {len(df_val)} imagenes')
print()
print('Distribucion en entrenamiento:')
print(df_train['label'].value_counts())

"""---
## PASO 7 — Preprocesamiento y Data Augmentation

**Preprocesamiento:** normalizar pixels de [0-255] a [0-1] y redimensionar a 224x224.

**Data Augmentation:** aplicar transformaciones aleatorias para aumentar variedad y reducir overfitting:
rotaciones, desplazamientos, volteo horizontal, zoom y corte.

"""

IMG_SIZE   = (224, 224)
BATCH_SIZE = 32
EPOCHS     = 30
LR         = 0.001

# Generador de entrenamiento CON augmentation
datagen_train = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    zoom_range=0.2,
    shear_range=0.1,
    fill_mode='nearest'
)

# Generador de validacion SIN augmentation
datagen_val = ImageDataGenerator(rescale=1./255)

train_gen = datagen_train.flow_from_dataframe(
    dataframe=df_train,
    x_col='ruta',
    y_col='label',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=True
)

val_gen = datagen_val.flow_from_dataframe(
    dataframe=df_val,
    x_col='ruta',
    y_col='label',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

CLASES         = list(train_gen.class_indices.keys())
INDICE_A_CLASE = {v: k for k, v in train_gen.class_indices.items()}
NUM_CLASES     = len(CLASES)

print('Clases:', CLASES)
print('Numero de clases:', NUM_CLASES)

# Muestras de imagenes por clase
fig, axes = plt.subplots(NUM_CLASES, 5, figsize=(15, 3 * NUM_CLASES))
fig.suptitle('Muestras de imagenes por clase', fontsize=14, fontweight='bold')

for i, clase in enumerate(CLASES):
    rutas_clase = df[df['label'] == clase]['ruta'].values
    for j in range(5):
        ax = axes[i][j]
        if j < len(rutas_clase):
            try:
                img = load_img(rutas_clase[j], target_size=(150, 150))
                ax.imshow(img)
            except:
                ax.text(0.5, 0.5, 'Error', ha='center', va='center')
        ax.axis('off')
        if j == 0:
            ax.set_title(clase, fontsize=10, fontweight='bold', loc='left')

plt.tight_layout()
plt.savefig('muestras_por_clase.png', bbox_inches='tight')
plt.show()

"""---
## PASO 8 — Arquitectura de la CNN

La red tiene 4 bloques convolucionales seguidos de capas densas:

```
Entrada (224x224x3)
  Bloque 1: Conv2D(32)  + BatchNorm + MaxPool -> 112x112
  Bloque 2: Conv2D(64)  + BatchNorm + MaxPool -> 56x56
  Bloque 3: Conv2D(128) + BatchNorm + MaxPool -> 28x28
  Bloque 4: Conv2D(256) + BatchNorm + MaxPool -> 14x14
  Flatten
  Dense(512) + Dropout(0.5)
  Dense(256) + Dropout(0.3)
  Dense(4)   + Softmax
```

"""

modelo = Sequential(name='CNN_Pollos')

# Bloque 1: detecta bordes y texturas simples
modelo.add(Conv2D(32, (3,3), activation='relu', padding='same',
                  input_shape=(224, 224, 3)))
modelo.add(BatchNormalization())
modelo.add(MaxPooling2D(2, 2))

# Bloque 2: detecta esquinas y curvas
modelo.add(Conv2D(64, (3,3), activation='relu', padding='same'))
modelo.add(BatchNormalization())
modelo.add(MaxPooling2D(2, 2))

# Bloque 3: detecta formas y partes del objeto
modelo.add(Conv2D(128, (3,3), activation='relu', padding='same'))
modelo.add(BatchNormalization())
modelo.add(MaxPooling2D(2, 2))

# Bloque 4: representaciones abstractas especificas por enfermedad
modelo.add(Conv2D(256, (3,3), activation='relu', padding='same'))
modelo.add(BatchNormalization())
modelo.add(MaxPooling2D(2, 2))

# Clasificador
modelo.add(Flatten())
modelo.add(Dense(512, activation='relu'))
modelo.add(Dropout(0.5))
modelo.add(Dense(256, activation='relu'))
modelo.add(Dropout(0.3))
modelo.add(Dense(NUM_CLASES, activation='softmax'))

modelo.compile(
    optimizer=Adam(learning_rate=LR),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

modelo.summary()
print(f'Parametros totales: {modelo.count_params():,}')

"""---
## PASO 9 — Entrenamiento

| Callback | Funcion |
|----------|---------|
| EarlyStopping | Para si val_loss no mejora en 7 epocas |
| ReduceLROnPlateau | Reduce LR a la mitad si no mejora en 3 epocas |
| ModelCheckpoint | Guarda el mejor modelo automaticamente |

"""

callbacks = [
    EarlyStopping(
        monitor='val_loss', patience=7,
        restore_best_weights=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.5,
        patience=3, min_lr=1e-6, verbose=1
    ),
    ModelCheckpoint(
        filepath='mejor_modelo.h5',
        monitor='val_accuracy',
        save_best_only=True, verbose=1
    )
]

print('Iniciando entrenamiento...')
print(f'Train: {len(df_train)} imagenes | Val: {len(df_val)} imagenes')
print('='*60)

historia = modelo.fit(
    train_gen,
    epochs=EPOCHS,
    validation_data=val_gen,
    callbacks=callbacks,
    verbose=1
)

mejor_acc   = max(historia.history['val_accuracy'])
epocas_reales = len(historia.history['accuracy'])
print()
print('='*60)
print('ENTRENAMIENTO FINALIZADO')
print(f'Epocas ejecutadas:  {epocas_reales}')
print(f'Mejor val_accuracy: {mejor_acc:.4f} ({mejor_acc*100:.2f}%)')

"""---
## PASO 10 — Curvas de entrenamiento

- **Buen ajuste:** train y val suben juntas
- **Overfitting:** train sube pero val se estanca o baja
- **Underfitting:** ambas son bajas

"""

hist   = historia.history
epocas = range(1, len(hist['accuracy']) + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle('Curvas de Entrenamiento', fontsize=14, fontweight='bold')

axes[0].plot(epocas, hist['accuracy'],     'b-o', label='Train', markersize=4)
axes[0].plot(epocas, hist['val_accuracy'], 'r-o', label='Val',   markersize=4)
axes[0].set_title('Accuracy')
axes[0].set_xlabel('Epoca')
axes[0].set_ylabel('Accuracy')
axes[0].legend()
axes[0].set_ylim([0, 1])
axes[0].grid(True, alpha=0.3)

axes[1].plot(epocas, hist['loss'],     'b-o', label='Train', markersize=4)
axes[1].plot(epocas, hist['val_loss'], 'r-o', label='Val',   markersize=4)
axes[1].set_title('Loss')
axes[1].set_xlabel('Epoca')
axes[1].set_ylabel('Loss')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('curvas_entrenamiento.png', bbox_inches='tight')
plt.show()

# Diagnostico automatico
diff = hist['accuracy'][-1] - hist['val_accuracy'][-1]
print('DIAGNOSTICO:')
if diff > 0.15:
    print('OVERFITTING: diferencia train-val =', round(diff, 4))
    print('Sugerencia: mas Dropout o mas augmentation')
elif hist['accuracy'][-1] < 0.7:
    print('UNDERFITTING: accuracy baja =', round(hist['accuracy'][-1], 4))
    print('Sugerencia: mas epocas o arquitectura mas profunda')
else:
    print('Buen ajuste. El modelo aprende correctamente.')
print(f'Train final: {hist["accuracy"][-1]:.4f} | Val final: {hist["val_accuracy"][-1]:.4f}')

"""---
## PASO 11 — Evaluacion y Metricas

| Metrica | Formula | Significado |
|---------|---------|-------------|
| Accuracy | (TP+TN)/Total | Predicciones correctas totales |
| Precision | TP/(TP+FP) | Cuantas predicciones positivas son correctas |
| Recall | TP/(TP+FN) | Cuantos positivos reales se detectaron |
| F1-Score | 2*(P*R)/(P+R) | Balance entre precision y recall |

"""

modelo_final = tf.keras.models.load_model('mejor_modelo.h5')

print('Generando predicciones sobre el conjunto de validacion...')
val_gen.reset()

predicciones_proba = modelo_final.predict(val_gen, verbose=1)
y_pred_indices     = np.argmax(predicciones_proba, axis=1)
y_pred_nombres     = [INDICE_A_CLASE[i] for i in y_pred_indices]
y_real_nombres     = df_val['label'].values

accuracy_final = accuracy_score(y_real_nombres, y_pred_nombres)

print()
print('='*60)
print(f'ACCURACY FINAL: {accuracy_final:.4f} ({accuracy_final*100:.2f}%)')
print('='*60)
print()
print('REPORTE POR CLASE:')
print(classification_report(y_real_nombres, y_pred_nombres, digits=4))

"""---
##  — Métricas de Regresión vs Clasificación

En Machine Learning existen dos tipos principales de problemas y cada uno
tiene sus propias métricas de evaluación:

---

### Clasificación (nuestro proyecto)
Se usa cuando la salida es una CATEGORIA o ETIQUETA discreta.
Ejemplo: ¿Qué enfermedad tiene el pollo? → Salmonella / Coccidiosis / Healthy / NCD

| Métrica | Fórmula | Qué mide |
|---------|---------|----------|
| **Accuracy** | (TP+TN) / Total | % de predicciones correctas totales |
| **Precision** | TP / (TP+FP) | De los que predije como X, cuántos SÍ eran X |
| **Recall** | TP / (TP+FN) | De los que eran X, cuántos logré detectar |
| **F1-Score** | 2*(P*R)/(P+R) | Balance entre Precision y Recall |

Donde: TP=Verdaderos Positivos, FP=Falsos Positivos, FN=Falsos Negativos

**¿Cuándo usar F1 en vez de Accuracy?**
Cuando el dataset está desbalanceado (una clase tiene muchos más ejemplos que otras).
En nuestro caso, New Castle Disease tiene solo 562 imágenes vs 2625 de Salmonella,
por eso el F1-Score es más confiable que el Accuracy.

---

### Regresión
Se usa cuando la salida es un NÚMERO CONTINUO.
Ejemplo: ¿Cuánto pesará el pollo en 30 días? → 2.3 kg / 1.8 kg / 3.1 kg

| Métrica | Fórmula | Qué mide |
|---------|---------|----------|
| **MAE** | Media( |real - predicho| ) | Error promedio en las mismas unidades |
| **MSE** | Media( (real - predicho)² ) | Penaliza más los errores grandes |
| **RMSE** | Raíz cuadrada del MSE | Error en las mismas unidades que MSE |
| **R²** | 1 - (SS_res / SS_tot) | Qué % de la variación explica el modelo |

**¿Cuándo usar cuál?**
- MAE → cuando todos los errores son igual de importantes
- MSE/RMSE → cuando los errores grandes son muy costosos (ej: diagnóstico médico)
- R² → para saber qué tan bien el modelo explica los datos (1.0 = perfecto, 0 = no explica nada)
"""

# Comparacion visual: Clasificacion vs Regresion
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle('Metricas: Clasificacion vs Regresion', fontsize=14, fontweight='bold')

# ─── PANEL IZQUIERDO: Clasificacion ───────────────────────────────────────────
ax1 = axes[0]
ax1.set_xlim(0, 10)
ax1.set_ylim(0, 10)
ax1.axis('off')
ax1.set_title('CLASIFICACION', fontsize=13, fontweight='bold', color='#2980b9', pad=15)

metricas_clf = [
    ('ACCURACY',  '#3498db', 'Predicciones correctas totales\n(TP + TN) / Total\nEjemplo: 85% de imagenes bien clasificadas'),
    ('PRECISION', '#2ecc71', 'De los que predije como Salmonella\ncuantos realmente tenian Salmonella\nTP / (TP + FP)'),
    ('RECALL',    '#e67e22', 'De todos los casos reales de Salmonella\ncuantos logre detectar\nTP / (TP + FN)'),
    ('F1-SCORE',  '#9b59b6', 'Balance entre Precision y Recall\nIdeal cuando el dataset esta desbalanceado\n2 * (P * R) / (P + R)'),
]

for i, (nombre, color, desc) in enumerate(metricas_clf):
    y = 8.5 - i * 2.1
    rect = plt.Rectangle((0.3, y - 0.45), 9.4, 1.7, color=color, alpha=0.15, zorder=1)
    ax1.add_patch(rect)
    ax1.text(0.6, y + 0.7, nombre, fontsize=11, fontweight='bold', color=color)
    ax1.text(0.6, y - 0.1, desc, fontsize=8.5, color='#2c3e50', linespacing=1.5)

# ─── PANEL DERECHO: Regresion ─────────────────────────────────────────────────
ax2 = axes[1]
ax2.set_xlim(0, 10)
ax2.set_ylim(0, 10)
ax2.axis('off')
ax2.set_title('REGRESION', fontsize=13, fontweight='bold', color='#c0392b', pad=15)

metricas_reg = [
    ('MAE',  '#e74c3c', 'Error Absoluto Medio\nMedia( |real - predicho| )\nFacil de interpretar. Ej: error promedio de 0.3 kg'),
    ('MSE',  '#e67e22', 'Error Cuadratico Medio\nMedia( (real - predicho)^2 )\nPenaliza errores grandes con mas fuerza'),
    ('RMSE', '#f39c12', 'Raiz del Error Cuadratico Medio\nRaiz cuadrada del MSE\nMismas unidades que la variable predicha'),
    ('R2',   '#27ae60', 'Coeficiente de Determinacion\n1 - (SS_residual / SS_total)\nR2=1: perfecto | R2=0: no explica nada'),
]

for i, (nombre, color, desc) in enumerate(metricas_reg):
    y = 8.5 - i * 2.1
    rect = plt.Rectangle((0.3, y - 0.45), 9.4, 1.7, color=color, alpha=0.15, zorder=1)
    ax2.add_patch(rect)
    ax2.text(0.6, y + 0.7, nombre, fontsize=11, fontweight='bold', color=color)
    ax2.text(0.6, y - 0.1, desc, fontsize=8.5, color='#2c3e50', linespacing=1.5)

plt.tight_layout()
plt.savefig('metricas_clasificacion_vs_regresion.png', bbox_inches='tight')
plt.show()

# ─── Resumen en consola ────────────────────────────────────────────────────────
print('='*60)
print('RESUMEN DE METRICAS')
print('='*60)
print()
print('CLASIFICACION (este proyecto):')
print('  Accuracy  = predicciones correctas / total')
print('  Precision = TP / (TP + FP)')
print('  Recall    = TP / (TP + FN)')
print('  F1-Score  = 2 * (Precision * Recall) / (Precision + Recall)')
print()
print('REGRESION (valor numerico continuo):')
print('  MAE  = promedio de |real - predicho|')
print('  MSE  = promedio de (real - predicho)^2')
print('  RMSE = raiz cuadrada del MSE')
print('  R2   = 1 - (varianza residual / varianza total)')
print()
print('NUESTRO PROYECTO usa CLASIFICACION porque')
print('la salida es una categoria (nombre de enfermedad),')
print('no un numero continuo.')
print('='*60)

"""---
## PASO 12 — Matriz de Confusion

La diagonal principal son las predicciones correctas.
Los valores fuera de la diagonal son los errores.

"""

cm            = confusion_matrix(y_real_nombres, y_pred_nombres, labels=CLASES)
cm_normalizada = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('Matriz de Confusion', fontsize=14, fontweight='bold')

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASES, yticklabels=CLASES, ax=axes[0])
axes[0].set_title('Valores absolutos')
axes[0].set_xlabel('Clase Predicha')
axes[0].set_ylabel('Clase Real')
axes[0].tick_params(axis='x', rotation=30)

sns.heatmap(cm_normalizada, annot=True, fmt='.2%', cmap='Greens',
            xticklabels=CLASES, yticklabels=CLASES, ax=axes[1])
axes[1].set_title('Valores normalizados')
axes[1].set_xlabel('Clase Predicha')
axes[1].set_ylabel('Clase Real')
axes[1].tick_params(axis='x', rotation=30)

plt.tight_layout()
plt.savefig('matriz_confusion.png', bbox_inches='tight')
plt.show()

print('Recall por clase:')
for i, clase in enumerate(CLASES):
    correctas = cm[i][i]
    total     = cm[i].sum()
    print(f'  {clase:<25}: {correctas}/{total} ({correctas/total*100:.1f}%)')

"""---
## PASO 13 — Panel de predicciones visuales

Marco verde = prediccion correcta. Marco rojo = prediccion incorrecta.

"""

n_cols = 5
n_rows = 4
indices_muestra = np.random.choice(len(df_val), n_cols * n_rows, replace=False)
df_muestra      = df_val.iloc[indices_muestra].reset_index(drop=True)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(16, 13))
fig.suptitle('Predicciones del Modelo (verde=correcto, rojo=incorrecto)',
             fontsize=12, fontweight='bold')

for idx, (_, fila) in enumerate(df_muestra.iterrows()):
    ax = axes[idx // n_cols][idx % n_cols]
    try:
        img = load_img(fila['ruta'], target_size=IMG_SIZE)
        arr = np.expand_dims(img_to_array(img) / 255.0, axis=0)
        proba    = modelo_final.predict(arr, verbose=0)
        pred_idx = np.argmax(proba)
        pred_cls = INDICE_A_CLASE[pred_idx]
        confianza = proba[0][pred_idx] * 100
        correcto  = (pred_cls == fila['label'])
        color     = '#27ae60' if correcto else '#e74c3c'
        simbolo   = 'OK' if correcto else 'X'
        ax.imshow(img)
        ax.axis('off')
        for spine in ax.spines.values():
            spine.set_edgecolor(color)
            spine.set_linewidth(4)
            spine.set_visible(True)
        ax.set_title(f'{simbolo} {pred_cls[:12]}\n({confianza:.0f}%)',
                     fontsize=8, color=color, fontweight='bold')
    except Exception as e:
        ax.text(0.5, 0.5, 'Error', ha='center', va='center')
        ax.axis('off')

plt.tight_layout()
plt.savefig('predicciones_visuales.png', bbox_inches='tight')
plt.show()

"""---
## PASO 14 — Guardar y descargar el modelo

"""

import json

NOMBRE_MODELO = 'modelo_CNN_pollos_final.h5'
modelo_final.save(NOMBRE_MODELO)
print('Modelo guardado:', NOMBRE_MODELO)

config = {
    'clases':             CLASES,
    'indice_a_clase':     {str(k): v for k, v in INDICE_A_CLASE.items()},
    'img_size':           list(IMG_SIZE),
    'num_clases':         NUM_CLASES,
    'accuracy_final':     float(accuracy_final),
    'epocas_entrenadas':  len(historia.history['accuracy']),
    'mejor_val_accuracy': float(max(historia.history['val_accuracy'])),
    'dataset_train':      len(df_train),
    'dataset_val':        len(df_val)
}

with open('config_modelo.json', 'w') as f:
    json.dump(config, f, indent=4)
print('Config guardada: config_modelo.json')

print('Descargando archivos...')
files.download(NOMBRE_MODELO)
files.download('config_modelo.json')
files.download('curvas_entrenamiento.png')
files.download('matriz_confusion.png')
files.download('predicciones_visuales.png')
print('Listo!')

"""---
## PASO 15 — Resumen Final

"""

print('='*65)
print('  RESUMEN FINAL — CNN CLASIFICACION ENFERMEDADES EN POLLOS')
print('='*65)
print()
print('DATASET')
print(f'  Total imagenes:    {len(df):,}')
print(f'  Entrenamiento:     {len(df_train):,} (80%)')
print(f'  Validacion:        {len(df_val):,} (20%)')
print(f'  Clases:            {CLASES}')
print()
print('ARQUITECTURA')
print('  Tipo:              CNN Secuencial')
print('  Bloques Conv:      4 (32, 64, 128, 256 filtros)')
print('  Capas densas:      2 (512, 256 neuronas)')
print('  Regularizacion:    Dropout + BatchNormalization')
print(f'  Parametros:        {modelo_final.count_params():,}')
print()
print('ENTRENAMIENTO')
print(f'  Optimizador:       Adam (LR={LR})')
print('  Loss:              Categorical Crossentropy')
print(f'  Batch size:        {BATCH_SIZE}')
print(f'  Epocas ejecutadas: {len(historia.history["accuracy"])}')
print()
print('RESULTADOS')
print(f'  Mejor val_accuracy: {max(historia.history["val_accuracy"]):.4f} ({max(historia.history["val_accuracy"])*100:.2f}%)')
print(f'  Accuracy final:     {accuracy_final:.4f} ({accuracy_final*100:.2f}%)')
print()
print('ARCHIVOS GENERADOS')
print('  modelo_CNN_pollos_final.h5')
print('  config_modelo.json')
print('  curvas_entrenamiento.png')
print('  matriz_confusion.png')
print('  predicciones_visuales.png')
print('='*65)

"""##CONCLUSIONES GENERALES DEL PROYECTO         
##CNN - Clasificacion de Enfermedades en Pollos              

1. PROBLEMA RESUELTO
   Se desarrollo un modelo de inteligencia artificial capaz de
   clasificar imagenes de pollos en 4 categorias: Healthy,
   Coccidiosis, Salmonella y New Castle Disease, con un alto
   nivel de precision automatica.

2. TIPO DE DATOS
   Las CNN trabajan con datos NO estructurados (imagenes).
   A diferencia de las redes neuronales tradicionales que
   requieren datos estructurados en tablas, las CNN extraen
   sus propias caracteristicas directamente de los pixeles,
   sin necesidad de procesamiento manual previo.

3. ARQUITECTURA CNN
   Se implementaron 4 bloques convolucionales progresivos
   (32, 64, 128, 256 filtros) que aprenden caracteristicas
   de menor a mayor complejidad:
   - Bloque 1: bordes y texturas basicas
   - Bloque 2: esquinas y formas simples
   - Bloque 3: patrones especificos de cada enfermedad
   - Bloque 4: representaciones abstractas de alto nivel
   El uso de BatchNormalization estabilizo el entrenamiento
   y Dropout previno el overfitting eficazmente.

4. METRICAS DE CLASIFICACION (este proyecto)
   - Accuracy:  predicciones correctas sobre el total
   - Precision: calidad de las predicciones positivas
   - Recall:    capacidad de detectar casos reales
   - F1-Score:  balance entre Precision y Recall
   El F1-Score fue clave dado el desbalance entre clases
   (New Castle Disease con solo 562 imagenes vs 2625 de Salmonella).

5. METRICAS DE REGRESION (problemas de valor continuo)
   - MAE:  error promedio en las mismas unidades
   - MSE:  penaliza errores grandes
   - RMSE: error interpretable en unidades reales
   - R2:   porcentaje de variacion explicada por el modelo

6. TECNICAS APLICADAS
   - Data Augmentation: aumento artificial del dataset con
     rotaciones, zoom y volteos para mejorar generalizacion
   - EarlyStopping: detuvo el entrenamiento en el punto optimo
   - ReduceLROnPlateau: ajuste dinamico de la tasa de aprendizaje
   - ModelCheckpoint: guardo automaticamente el mejor modelo

7. IMPACTO Y APLICACIONES REALES
   Un sistema como este puede:
   - Detectar enfermedades en etapas tempranas
   - Reducir perdidas economicas en granjas avicolas
   - Reemplazar diagnosticos manuales lentos y costosos
   - Escalarse a drones o camaras automatizadas en campo

8. LIMITACIONES Y TRABAJO FUTURO
   - New Castle Disease tiene pocas imagenes (562), lo que
     puede afectar su precision de deteccion
   - Se podria mejorar usando Transfer Learning con modelos
     preentrenados como MobileNetV2 o ResNet50
   - Una app movil permitiria usar el modelo en campo real



* CONCLUSION FINAL:
  La CNN logro aprender a distinguir enfermedades aviares
  directamente desde imagenes crudas, sin intervencion humana
  en la extraccion de caracteristicas. Esto demuestra que el
  Deep Learning es una herramienta poderosa y viable para
  resolver problemas reales en agricultura e industria avicola.
"""

